### ISSUE TITLE
SNMP Binding should use a port above 1024

### ISSUE THREAD

**Issue by Rick-Jongbloed** [ricadelic/ricks-openhab-config#3]
Setcap is not supported in docker for odroid c2, therefore i cannot set the xattr that allows the binding to port 162 in the openhab user context.

Solution: Use a port above 162 and map it to the host (if possible)

**Comment by Rick-Jongbloed** [comment]
2019-04-26 23:05:37.611 [ERROR] [ab.binding.snmp.internal.SnmpBinding] - SNMP binding couldn't listen to 0.0.0.0/162
java.net.BindException: Permission denied (Bind failed)
        at java.net.PlainDatagramSocketImpl.bind0(Native Method) ~[?:?]
        at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93) ~[?:?]
        at java.net.DatagramSocket.bind(DatagramSocket.java:392) ~[?:?]
        at java.net.DatagramSocket.<init>(DatagramSocket.java:242) ~[?:?]
        at java.net.DatagramSocket.<init>(DatagramSocket.java:299) ~[?:?]
        at org.snmp4j.transport.DefaultUdpTransportMapping.<init>(DefaultUdpTransportMapping.java:101) ~[261:org.openhab.binding.snmp:1.14.0.M1]
        at org.openhab.binding.snmp.internal.SnmpBinding.listen(SnmpBinding.java:131) [261:org.openhab.binding.snmp:1.14.0.M1]
        at org.openhab.binding.snmp.internal.SnmpBinding.updated(SnmpBinding.java:442) [261:org.openhab.binding.snmp:1.14.0.M1]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updated(ManagedServiceTracker.java:189) [9:org.apache.felix.configadmin:1.9.10]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.updateService(ManagedServiceTracker.java:152) [9:org.apache.felix.configadmin:1.9.10]
        at org.apache.felix.cm.impl.helper.ManagedServiceTracker.provideConfiguration(ManagedServiceTracker.java:85) [9:org.apache.felix.configadmin:1.9.10]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.provide(ConfigurationManager.java:1113) [9:org.apache.felix.configadmin:1.9.10]
        at org.apache.felix.cm.impl.ConfigurationManager$ManagedServiceUpdate.run(ConfigurationManager.java:1069) [9:org.apache.felix.configadmin:1.9.10]
        at org.apache.felix.cm.impl.UpdateThread.run0(UpdateThread.java:138) [9:org.apache.felix.configadmin:1.9.10]
        at org.apache.felix.cm.impl.UpdateThread.run(UpdateThread.java:105) [9:org.apache.felix.configadmin:1.9.10]
        at java.lang.Thread.run(Thread.java:748) [?:?]
